### ISSUE TITLE
Question concerning packaged Clariom D CDF

### ISSUE THREAD

**Issue by mforde84** [jpromeror/EventPointer#1]
Hello,

I'm looking to use EventPointer to assess alternate splicing events on Clariom D human. I've read some of the documentation regarding generating a CDF for annotation, however Bioconductor already has a packaged CDF available for a probe level analysis either with pd.clariom.d.human or clariomdhumanprobeset.db. I'm curious if it's possible to used these packages instead of manually generating the CDF outlined in your readme.

Thanks,
Martin

**Comment by jpromeror** [comment]
Hello Martin,

The main difference between those annotation packages and the CDF file that is created by EventPointer, is that in the CDF file, has the different probes grouped by the different alternative splicing events detected using EventPointer methodology.

I haven't tried to use the information contained in the annotation packages you mention to create the required files for analysis. I will give it a look.

Also, we've already created the CDF file for the Clariom-D array. I could send it to you or upload it to the dropbox url depicted in the vignette.

Thank you,

Juan Pablo Romero

**Comment by mforde84** [comment]
Hi Juan,

That would be great if you could share the CDF file you have for Clariom-D human. Eventually I'll want to generate one myself just to become a little clearer on the process, however at the moment we just want to test with a sample data set for the purpose of included an analysis strategy into a grant. So if we could rapidly generate proof of concept for the analysis, I think that would be great. Only so much time in the day, and I've been having trouble locating some of the pertinent information from Affy's annotation resources, so any help in this matter is definitely appreciated.

**Comment by jpromeror** [comment]
Hi Martin,

Here is the link to the dropbox folder:

https://www.dropbox.com/sh/wpwz1jx0l112icw/AAAOU0M2QS0TjqHAhrrdEhp6a?dl=0

In the Clariom folder you can find the following files:

1) ClariomD.zip
    - JunctionProbes.txt
    - PSRProbes.txt
    - Clariom_Transcripts.gtf

2) ClariomD.cdf

The files contained in the .zip are the ones used to create the CDF and also used to generate the visualization for IGV.

I haven't mentioned this in the vignette or other places because currently we are make some minor changes. We also are planning to include the files for the MTA (mouse) and RTA (rat), the changes mostly will be related with this arrays, but first I wanted to have it available in bioconductor (currently is under revision) and then all the changes will be done.

Hope this helps!

Juan Pablo

**Comment by mforde84** [comment]
Thank you very much Juan. This is excellent. Really appreciate it.
